apiVersion: v1
kind: ConfigMap
metadata:
  name: knative-configmap
data:
#  protocol: "DMERGE"
#  protocol: "DMERGE_PUSH"
  protocol: "S3"
  trainerNum: "8"
  logLevel: "INFO"
  heapSizeHex: "40000000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: source
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-source
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "source"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: TRAINER_NUM
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: trainerNum
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pca-0
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "pca"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: BASE_HEX
              value: "140000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-0
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "0"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: BASE_HEX
              value: "180000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "1"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "2A0000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "2"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "2F0000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-3
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "3"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "340000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-4
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "4"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "390000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-5
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "3"
            - name: UPSTREAM_NUM
              value: "5"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "3E0000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-6
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "6"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "430000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer-7
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 1
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"
            - name: ID
              value: "7"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: BASE_HEX
              value: "540000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              value: "/usr/local/share/libmalloc_wrapper.so"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: combinemodels
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "combinemodels"
            - name: ID
              value: "0"
            - name: UPSTREAM_NUM
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: trainerNum
            - name: LOG_LEVEL
              value: "INFO"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
#            - name: BASE_HEX
#              value: "150000000"
#            - name: TOTAL_SZ_HEX
#              value: "40000000"
#            - name: LD_PRELOAD
#              value: "/usr/local/share/libmalloc_wrapper.so"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-ml-pipeline
          image: val01:5000/dmerge-ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "sink"
            - name: ID
              value: "0"
            - name: UPSTREAM_NUM
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
# Main body of MapReduce-alike framework
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: source
    - ref: # Parallel for mapper. Note!!!: Parallel shall not be followed by other seq services
        apiVersion: flows.knative.dev/v1
        kind: Parallel
        name: pca-parallel
---
# Workflow related
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: pca-parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: pca-0
  reply:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Parallel
      name: trainer-parallel
---
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: trainer-parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-0
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-1
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-2
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-3
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-4
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-5

    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-6
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: trainer-7
  reply:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: combine-sequence
---
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: combine-sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: combinemodels
  reply:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default-broker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ping-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: dev.knative.sources.ping # Default ping type from Ping-Source
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: sequence
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: none
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sink-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: combinemodels
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sink