
[[pass]]
host = "val06"
path = '/home/lfm/projects/dmerge'
cmd  = 'sudo rm -r /dev/mitosis-syscalls/'
[[pass]]
host = "val07"
path = '/home/lfm/projects/dmerge'
cmd  = 'sudo rm -r /dev/mitosis-syscalls/'

