FROM python:3.7.11-buster as Build

ARG ACCESS_TOKEN=token

WORKDIR /usr/src
RUN git clone https://docker:${ACCESS_TOKEN}@ipads.se.sjtu.edu.cn:1312/distributed-rdma-serverless/distributed-merge/cpython.git my_python_repo && \
    cd my_python_repo && \
    git checkout 3.7 && \
    mkdir build && cd build && \
    ../configure --with-pydebug && \
    make -j$(nproc) && \
    make install



