FROM caribouf/cpython-build as build

WORKDIR /app

# Install dependencies
RUN echo "cython" >> requirements.txt && \
    echo "numpy==1.19.3" >> requirements.txt && \
    echo "Flask==2.0.3" >> requirements.txt && \
    echo "requests" >> requirements.txt && \
    echo "yfinance" >> requirements.txt && \
    echo "cloudevents==1.9.0" >> requirements.txt && \
    echo "redis" >> requirements.txt && \
    echo "lightgbm==2.0.7" >> requirements.txt && \
    echo "minio" >> requirements.txt && \
    pip install -r requirements.txt