FROM caribouf/cpython-build as build

WORKDIR /usr/src
RUN echo "Flask==2.0.3" >> requirements.txt \
    && echo "requests" >> requirements.txt \
    && echo "cloudevents" >> requirements.txt \
    && echo "redis" >> requirements.txt \
    && echo "numpy==1.21.6" >> requirements.txt \
    && echo "yfinance" >> requirements.txt \
    && echo "lightgbm==2.0.7" >> requirements.txt

RUN python -m pip install -r requirements.txt

WORKDIR /app

CMD ["python", "--version"]