FROM caribouf/cpython-build as build

WORKDIR /app

# Install dependencies
RUN echo "cython" >> requirements.txt && \
    echo "pillow==7.0.0" >> requirements.txt && \
    echo "numpy==1.19.3" >> requirements.txt && \
    echo "opencv-python==4.2.0.32" >> requirements.txt && \
    echo "torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu" >> requirements.txt && \
    echo "torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cpu" >> requirements.txt && \
    echo "pytest==7.1.3" >> requirements.txt && \
    echo "tqdm==4.64.1" >> requirements.txt && \
    echo "matplotlib==3.3.2" >> requirements.txt && \
    echo "mock==4.0.3" >> requirements.txt && \
    echo "imageai==2.1.6" >> requirements.txt && \
    echo "Flask==2.0.3" >> requirements.txt && \
    echo "requests==2.27.1" >> requirements.txt && \
    echo "cloudevents==1.9.0" >> requirements.txt && \
    echo "redis" >> requirements.txt && \
    echo "lightgbm==2.0.7" >> requirements.txt && \
    echo "minio" >> requirements.txt && \
    pip install -r requirements.txt