apiVersion: v1
kind: ConfigMap
metadata:
  name: knative-configmap
data:
#  protocol: "DMERGE"
#  protocol: "DMERGE_PUSH"
  protocol: "RPC"
#  protocol: "ES"

  logLevel: "INFO"
  heapSizeHex: "40000000"
  touchRatio: "10"
  consumerNum: "1"
#  LD_PRELOAD: "/usr/local/share/libmalloc_wrapper.so"
  LD_PRELOAD: ""
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: splitter
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-micro
          image: val01:5000/dmerge-micro
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "splitter"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: producer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-micro
          image: val01:5000/dmerge-micro
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 0
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "producer"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: BASE_HEX
              value: "100000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: LD_PRELOAD
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
            - name: TOUCH_RATIO
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: touchRatio
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-0
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-micro
          image: val01:5000/dmerge-micro
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 0
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "consumer"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: BASE_HEX
              value: "140000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: LD_PRELOAD
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-micro
          image: val01:5000/dmerge-micro
          resources:
            limits:
              hostdev.k8s.io/dev_mitosis-syscalls: 0
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "1"
            - name: CE_TYPE
              value: "consumer"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: BASE_HEX
              value: "190000000"
            - name: TOTAL_SZ_HEX
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: heapSizeHex
            - name: LD_PRELOAD
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: LD_PRELOAD
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: user-app
          image: val01:5000/dmerge-micro
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "sink"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: logLevel
            - name: UPSTREAM_NUM
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: consumerNum
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: knative-configmap
                  key: protocol
---
# Main body of MapReduce-alike framework
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: start
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: splitter
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: producer
    - ref:
        apiVersion: flows.knative.dev/v1
        kind: Parallel
        name: consumer-parallel
---
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: consumer-parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: consumer-0
#    - subscriber:
#        ref:
#          apiVersion: serving.knative.dev/v1
#          kind: Service
#          name: consumer-1
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sink
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ping-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: dev.knative.sources.ping # Default ping type from Ping-Source
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: start
