apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostdev-device-plugin
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: hostdev-device-plugin-ds
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      hostNetwork: true
      containers:
        - name: hostdev
#          image: ccr.ccs.tencentyun.com/paas/hostdev:latest
          image: caribouf/k8s-hostdev-plugin:0.1
          args: ["--devs", "/dev/mitosis-syscalls:rwm"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
            - name: mitosis
              mountPath: /dev/mitosis-syscalls
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: mitosis
          hostPath:
            path: /dev/mitosis-syscalls
  selector:
    matchLabels:
      name: hostdev-device-plugin-ds