apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rust-demo
spec:
  template:
    spec:
      containers:
        - image: caribouf/helloworld-rust
          env:
            - name: CeType
              value: "splitter"
            - name: ServiceName
              value: "rust-trigger"
          volumeMounts:
            - name: device
              mountPath: /dev/mitosis-syscalls
