apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: splitter
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-p2p
          image: caribouf/dmerge-p2p
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "splitter"
            - name: LOG_LEVEL
              value: "DEBUG"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: producer-0
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-p2p
          image: caribouf/dmerge-p2p
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "0"
            - name: CE_TYPE
              value: "producer"
            - name: LOG_LEVEL
              value: "DEBUG"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: producer-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Credit to https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-p2p
          image: caribouf/dmerge-p2p
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: ID
              value: "1"
            - name: CE_TYPE
              value: "producer"
            - name: LOG_LEVEL
              value: "DEBUG"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - name: dmerge-p2p
          image: caribouf/dmerge-p2p
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "consumer"
            - name: ID
              value: "0"
            - name: UPSTREAM_NUM
              value: "2"
            - name: LOG_LEVEL
              value: "DEBUG"
---
# Main body of MapReduce-alike framework
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref: # Spliter
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: splitter
    - ref: # Parallel for mapper. Note!!!: Parallel shall not be followed by other seq services
        apiVersion: flows.knative.dev/v1
        kind: Parallel
        name: producer-parallel
---
# Workflow related
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: producer-parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: producer-0
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: producer-1
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: consumer
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ping-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: dev.knative.sources.ping # Default ping type from Ping-Source
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: sequence
