apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: default
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: [ "sleep", "9999999" ]
---
# A default broker
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default-broker
  namespace: default
  annotations:
    # Note: you can set the eventing.knative.dev/broker.class annotation to change the class of the broker.
    # The default broker class is MTChannelBasedBroker, but Knative also supports use of the other class.
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec: { }
---
apiVersion: sources.knative.dev/v1beta2
kind: PingSource
metadata:
  name: ping-source
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world From PingSource"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default-broker