apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: splitter
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline
          image: caribouf/ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "splitter"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trainer
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline
          image: caribouf/ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "trainer"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reducer
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline
          image: caribouf/ml-pipeline
          imagePullPolicy: Always
          env:
            - name: CE_SPECVERSION
              value: "0.3"
            - name: CE_TYPE
              value: "reducer"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.lank8s.cn/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---

# Workflow related
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: splitter
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: trainer
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: reducer
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
# Trigger of ping message
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ping-trigger
  namespace: default
spec:
  broker: default-broker
  filter:
    attributes:
      type: dev.knative.sources.ping # Default ping type from Ping-Source
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: sequence
